Since the Wordpress Admin uses jQuery UI we need to avoid using the `autocomplete` which is used by both jQuery UI and devbridge/jQuery-Autocomplete. Thus renamed to `devbridgeAutocomplete` as suggested https://github.com/devbridge/jQuery-Autocomplete#known-issues. Fixes #14 `Uncaught TypeError: $(...).autocomplete is not a function` (https://github.com/alexis-magina/cmb2-field-post-search-ajax/issues/14).